### PR TITLE
Fix error with first at range operator

### PR DESCRIPTION
**Pull request by dz-s**
#2

### CODE REVIEW

**Comment by zwbetz-gh** [comment]
As far as the issue you opened: Hugo's quickstart was written to work with one particular theme. So you should not expect other themes to just work out-of-the-box. In my theme's docs, I say that at least one menu item is required in the config file.

Now, I think your change is still good, say for the scenario where someone doesn't specify a menu in their config file (as you've experienced). 

Thanks for contributing this.

**Comment by dz-s** [comment]
@zwbetz-gh btw, don't you think, that it would be really cool to try to unify all the themes? For example, your theme uses "post" folder, but the other uses "posts" etc.

**Comment by zwbetz-gh** [comment]
@teriyakigod2 It would be cool, but it's unrealistic. I think the themes are too diverse. A user should refer to a theme's docs and `exampleSite` for configuration guidance. 

> For example, your theme uses "post" folder, but the other uses "posts" etc.

This can be easily changed. A user would just need to override the homepage template and replace `post` with whatever their folder was named.

**Comment by zwbetz-gh** [comment]
I've updated the [example site layout](https://github.com/zwbetz-gh/minimal-bootstrap-hugo-theme#example-site-layout) section of the README to reflect this.

**Pull request merged**
